language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

script:
    - vendor/bin/tester tests -s -p php $FLAGS
    - php code-checker/src/code-checker.php --short-arrays -d src

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --dev --prefer-source
    - composer create-project nette/code-checker code-checker ~2.5 --no-interaction --prefer-source
    - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then FLAGS="-d extension=xdebug.so --coverage coverage.xml --coverage-src src"; fi;

after_script:
    - |
        if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.xml
        fi

notifications:
    hipchat: 289b602f1aeee1bfec2a530bf1a759@Sunfox
