language: php
php:
    - 7.1

script:
    - vendor/bin/tester tests -s -p php $FLAGS

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --dev --prefer-source
    - if [[ "$TRAVIS_PHP_VERSION" = "7.1" ]]; then FLAGS="-d extension=xdebug.so --coverage coverage.xml --coverage-src src"; fi;

after_script:
    - |
        if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.xml
        fi
